rvm:
  - 1.9.3
  - 1.9.2

before_install:
  - gem install bundler --pre

before_script:
  - "bundle exec rake db:schema:load"
  - "bundle exec rake db:test:prepare"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
